# Generated by Django 5.0.2 on 2024-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serialno', models.IntegerField(primary_key=True, serialize=False)),
                ('Bookname', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('publishedDate', models.DateField()),
                ('Booktype', models.CharField(max_length=20)),
            ],
        ),
    ]
